#! /usr/bin/perl

use strict;
use Cwd;
use File::Basename;
use File::Spec;

sub magic_number_matches {
  return 0 unless -e '_build/magicnum';
  local *FH;
  open FH, '_build/magicnum' or return 0;
  my $filenum = <FH>;
  close FH;
  return $filenum == 628762;
}

my $progname;
my $orig_dir;
BEGIN {
  $^W = 1;  # Use warnings
  $progname = basename($0);
  $orig_dir = Cwd::cwd();
  my $base_dir = '/home/nhansen/projects/bard_binomial/bard';
  if (!magic_number_matches()) {
    unless (chdir($base_dir)) {
      die ("Couldn't chdir($base_dir), aborting\n");
    }
    unless (magic_number_matches()) {
      die ("Configuration seems to be out of date, please re-run 'perl Build.PL' again.\n");
    }
  }
  unshift @INC,
    (
     '/home/nhansen/projects/bard_binomial/bard/_build/lib',
     '/usr/local/gtb/lib/perl5',
     '/home/cruzp/src/tgseq/lib',
     '/home/cruzp/src/medseq/web',
     '/home/nhansen/projects/nfhsrc/lib',
     '/usr/local/gtb/vendor/lib/perl5/x86_64-linux-thread-multi',
     '/usr/local/gtb/vendor/lib/perl5',
     '/home/cherukur/lib',
     '/home/cruzp/workspace/medseq/lib',
     '/home/teerj/lib/perl5',
     '/home/cruzp/src/lib/perllib/lib/perl5',
     '/home/nhansen/INSTALL/Math-Pari-2.010801/blib/lib',
     '/home/nhansen/INSTALL/pari-2.3.4',
     '/home/nhansen/INSTALL/Math-Pari-2.010801/blib/arch/auto/Math/Pari',
     '/home/nhansen/projects/pools/varscan/VarScan-1.03/lib',
     '/home/nhansen/projects/nfhsrc/sambam/BioPerl-1.6.0',
     '/home/nhansen/projects/nfhsrc/sambam/Bio-SamTools-1.07/lib',
     '/home/nhansen/projects/nfhsrc/sambam/Bio-SamTools-1.07/blib/arch/auto/Bio/DB/Sam',
     '/home/nhansen/projects/github/MSPrep/lib'
    );
}

close(*DATA) unless eof(*DATA); # ensure no open handles to this script

use My::Build;

# Some platforms have problems setting $^X in shebang contexts, fix it up here
$^X = Module::Build->find_perl_interpreter;

if (-e 'Build.PL' and not My::Build->up_to_date('Build.PL', $progname)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.\n";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = My::Build->resume (
  properties => {
    config_dir => '_build',
    orig_dir => $orig_dir,
  },
);

$build->dispatch;
